### ISSUE TITLE
Issue 14/09/18

### ISSUE THREAD

**Issue by emeraldng** [florenciasilva/modulo-npm-markdown-links#5]
¡HOLA!

¡Hola!

Leyendo tu código lo encontré lo siguiente: 

- [✔ ] Funciones modularizadas.

- [ ✔] Uso de promesas

- [✔ ] Los comandos de línea son funcionales y devuelven los analisis de las URL.

Yo veo bastante concreto tu código y cumple con las caracteristicas que nos pedían. <3

**Comment by florenciasilva** [comment]
¡Muchas gracias por el feedback, Esme! 😄
