### ISSUE TITLE
Issue de Mir

### ISSUE THREAD

**Issue by MirEnovi** [florenciasilva/modulo-npm-markdown-links#6]
### **Hola** Flo.
En general veo un código muy limpio y sencillo.
En la documentación muy bien, me llevo algunas ideas para mi propio readme jeje.
En el código:
- En la linea 4 faltan unos ";".
- En la linea 13 haces la lectura del file system, quizá esa parte podría ir mejor en una función.
- Tienes algunos casos donde la identación no corresponde. Si usar Visual Code S puedes identar tu file, con shift+alt+f. 
- Igual hay muchas variables declaradas con Let que pueden ser Const, no se si algunas sean necesarias en let, pero cambie a la azar un par y seguía corriendo n_nU.
- La función requestHTTP no tiene un return, seria problemático quizá a la hora de los test. 

**Creo que es todo, mucho éxito con tu siguiente alcance.**

**Comment by florenciasilva** [comment]
¡El tip de la indentación me viene genial! Y recordarme de los let y const, ya tengo adicción a siempre utilizar let 😦 

¡Muchas gracias, Mir!
